### ISSUE TITLE
Update extensions based on WSAL changes

### ISSUE THREAD

**Issue by DannyWPWS** [WPWhiteSecurity/wsal-extension-template#14]
Raising this ticket from https://github.com/WPWhiteSecurity/wp-security-audit-log-premium/issues/1046

We will have to update all extensions that use the following functions:

WpSecurityAuditLog::GetGlobalOption
WpSecurityAuditLog::SetGlobalOption

Also any usage of object WSAL_Models_Option needs to be replaced.

**Comment by DannyWPWS** [comment]
Ill confirm any changes needed in extensions here as I move through each extension - 

**WSAL BBPress** - No changes needed

**Comment by sdobreff** [comment]
No longer exists.
