### ISSUE TITLE
WSAL_Extension_Core cannot be singleton

### ISSUE THREAD

**Issue by martinkrcho** [WPWhiteSecurity/wsal-extension-template#6]
Class WSAL_Extension_Core cannot be instantiated as singleton using get_instance method. All extensions would use the same instance with the same language domain.

**Comment by DannyWPWS** [comment]
Im unsure how I would change this (tho im sure its not a large task) - however, if it is needed - I do have a question @martinkrcho 

If the core is the same in all extensions, and the core files use the same text-domain (which differs to the non-core files which can have there own domain), they what issue would having them all use the same instance cause?

**Comment by DannyWPWS** [comment]
Ok after a call with Martin I see what this is referring to standardising how we load files in WSAL as a whole, as some areas use autoloaders, some dont etc
